MVCGarage25/Models/Member.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCGarage25.Models
{
    /// <summary>
    /// Members of garage with or without parked vehicles in garage
    /// </summary>
    //[DisplayColumn("FullName", "FullName", false)]
    public class Member
    {
        [Key]
        public int Id { get; set; }

        [Required, Index("IX_MemberFullName", 1, IsUnique = true)]
        [StringLength(100)]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required, Index("IX_MemberFullName", 2, IsUnique = true)]
        [StringLength(100)]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [Display(Name = "Full name")]
        public string FullName { get { return LastName + ", " + FirstName; } }

        [Display(Name = "Member's parked vehicles")]
        virtual public List<Vehicle> ParkedVehicles { get; set; }
    }
}

MVCGarage25/Controllers/MembersController.cs
using MVCGarage25.DAL;
using MVCGarage25.Models;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVCGarage25.Controllers
{
    public class MembersController : Controller
    {
        private MVCGarage25Context db = new MVCGarage25Context();

        // POST: Members/Search
        public ActionResult Search(string membersearchtext)
        {
            membersearchtext = membersearchtext.ToLower();
            var members = db.Members
                .Where(m =>
                    m.FirstName.ToLower().Contains(membersearchtext) ||
                    m.LastName.ToLower().Contains(membersearchtext) 
                );
            ViewBag.SearchResultText = "Search with '" + membersearchtext + "' resulted in " + members.Count().ToString() + " members";
            return View(members.ToList());
        }

        // GET: Members
        public ActionResult Index()
        {
            return View(db.Members.ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException)
                {
                    var message = "Cannot insert duplicate key value (" + member.FullName + "). Try again.";
                    ModelState.AddModelError("", message);
                }
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException)
            {
                // Probably violation of referential integrity
                ViewBag.ErrorMessage = "Could not delete this member. Probably because this member has more vehicles parked in the garage.";
            }
            return View(member);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCGarage25/Controllers/VehiclesController.cs
using MVCGarage25.DAL;
using MVCGarage25.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVCGarage25.Controllers
{
    public class VehiclesController : Controller
    {
        private MVCGarage25Context db = new MVCGarage25Context();

        public delegate IEnumerable<T> OrderMethod<T, TKey>(Func<T, TKey> OrderColumn);

        // POST: Vehicles/Search
        public ActionResult Search(string vehiclesearchtext)
        {
            vehiclesearchtext = vehiclesearchtext.ToLower();
            var vehicles = db.Vehicles
                .Include(v => v.Member)
                .Include(v => v.VehicleType)
                .Where(v =>
                    v.BrandAndModel.ToLower().Contains(vehiclesearchtext) ||
                    v.Color.ToLower().Contains(vehiclesearchtext) ||
                    v.NumberOfWheels.ToString().ToLower().Contains(vehiclesearchtext) ||
                    v.RegistrationNumber.ToString().ToLower().Contains(vehiclesearchtext) ||
                    v.VehicleType.Type.ToLower().Contains(vehiclesearchtext) ||
                    v.Member.FirstName.ToLower().Contains(vehiclesearchtext) ||
                    v.Member.LastName.ToLower().Contains(vehiclesearchtext)
                //v.StartParkingTime.ToString().ToLower().Contains(vehiclesearchtext) ||
                //v.EndParkingTime.ToString().ToLower().Contains(vehiclesearchtext)
                //v.ParkingTime.ToString().ToLower().Contains(vehiclesearchtext) ||
                //v.ParkingCost.ToString().ToLower().Contains(vehiclesearchtext) ||
                //v.ParkingCostPerHour.ToString().ToLower().Contains(vehiclesearchtext)
                );
            ViewBag.DetailedView = true;
            ViewBag.SearchResultText = "Search with '" + vehiclesearchtext + "' resulted in " + vehicles.Count().ToString() + " vehicles";
            return View(vehicles.ToList());
        }

        // GET: Vehicles
        public ActionResult Index()
        {
            // Get view options

            bool detailedView = Request["view"] == "detailed";
            ViewBag.DetailedView = detailedView;
            string itemsToShow = Request["show"] ?? "all";
            ViewBag.Show = itemsToShow;

            var vehicles = db.Vehicles.Include(v => v.Member).Include(v => v.VehicleType);
            if (itemsToShow == "checkedin")
            {
                vehicles = vehicles.Where(v => v.EndParkingTime == null);
            }
            else if (itemsToShow == "checkedout")
            {
                vehicles = vehicles.Where(v => v.EndParkingTime != null);
            }

            // Get sorting options

            string sortColumn = Request["sortcolumn"] ?? "member";
            ViewBag.SortColumn = sortColumn;
            string sortOption = Request["sortoption"] ?? "ascending";
            ViewBag.SortOption = sortOption;
            var columns = new List<SelectListItem>();
            columns.Add(new SelectListItem() { Value = "memberfullname", Text = "Member's full name" });
            columns.Add(new SelectListItem() { Value = "memberfirstname", Text = "Member's first name" });
            columns.Add(new SelectListItem() { Value = "memberlastname", Text = "Member's last name" });
            columns.Add(new SelectListItem() { Value = "type", Text = "Vehicle type" });
            columns.Add(new SelectListItem() { Value = "regno", Text = "Registration number" });
            ViewBag.SortColumnList = columns;

            // This variant leads to a lot of duplicated code ... :-(

            //if (sortOption == "ascending")
            //{
            //    switch (sortColumn)
            //    {
            //        case "memberfirstname":
            //            vehicles = vehicles.OrderBy(v => v.Member.FirstName);
            //            break;
            //        case "memberlastname":
            //            vehicles = vehicles.OrderBy(v => v.Member.LastName);
            //            break;
            //        case "type":
            //            vehicles = vehicles.OrderBy(v => v.VehicleType.Type);
            //            break;
            //        case "regno":
            //            vehicles = vehicles.OrderBy(v => v.RegistrationNumber);
            //            break;
            //    }
            //}
            //else
            //{
            //    switch (sortColumn)
            //    {
            //        case "memberfirstname":
            //            vehicles = vehicles.OrderByDescending(v => v.Member.FirstName);
            //            break;
            //        case "memberlastname":
            //            vehicles = vehicles.OrderByDescending(v => v.Member.LastName);
            //            break;
            //        case "type":
            //            vehicles = vehicles.OrderByDescending(v => v.VehicleType.Type);
            //            break;
            //        case "regno":
            //            vehicles = vehicles.OrderByDescending(v => v.RegistrationNumber);
            //            break;
            //    }
            //}

            // This variant requires that we have declared this delegate:
            // public delegate IEnumerable<T> OrderMethod<T, TKey>(Func<T, TKey> OrderColumn);

            OrderMethod<Vehicle, string> orderMethod;
            Func<Vehicle, string> orderColumn;
            if (sortOption == "ascending")
            {
                orderMethod = vehicles.OrderBy;
            }
            else
            {
                orderMethod = vehicles.OrderByDescending;
            }
            switch (sortColumn)
            {
                case "memberfullname":
                    // FullName = LastName + FirstName
                    // Must combine these two columns manually,
                    // because LINQ can't order by a derived column
                    orderColumn = v => (v.Member.LastName + ", " + v.Member.FirstName);
                    break;
                case "memberfirstname":
                    orderColumn = v => v.Member.FirstName;
                    break;
                case "memberlastname":
                    orderColumn = v => v.Member.LastName;
                    break;
                case "type":
                    orderColumn = v => v.VehicleType.Type;
                    break;
                case "regno":
                    orderColumn = v => v.RegistrationNumber;
                    break;
                default:
                    orderColumn = v => (v.Member.LastName + ", " + v.Member.FirstName);
                    break;
            }
            var vehiclesToView = orderMethod(orderColumn).ToList();
            
            return View(vehiclesToView);
        }

        // GET: Vehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: Vehicles/CheckIn
        public ActionResult CheckIn()
        {
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FullName");
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type");
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CheckIn([Bind(Include = "Id,MemberId,VehicleTypeId,RegistrationNumber,StartParkingTime,EndParkingTime,NumberOfWheels,BrandAndModel,Color")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                vehicle.StartParkingTime = DateTime.Now;
                db.Vehicles.Add(vehicle);
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException e)
                {
                    ModelState.AddModelError("RegistrationNumber", e.GetBaseException().Message);
                }
            }
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FullName", vehicle.MemberId);
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            if (vehicle.IsCheckedOut)
            {
                return RedirectToAction("Details/" + vehicle.Id);
            }
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FullName", vehicle.MemberId);
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

MVCGarage25/Views/Members/Create.cshtml
@model MVCGarage25.Models.Member

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCGarage25/Views/Members/Delete.cshtml
@model MVCGarage25.Models.Member

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ViewBag.ErrorMessage<br />
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCGarage25/Views/Members/Details.cshtml
@model MVCGarage25.Models.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        @*nytt*@
        <dt>
            @Html.DisplayNameFor(x => x.ParkedVehicles) (checked in)

        <dd>
            <table>
                @foreach (var vehicle in Model.ParkedVehicles)
                {
                    if (!vehicle.IsCheckedOut)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => vehicle.RegistrationNumber) |
                                @Html.DisplayFor(modelItem => vehicle.VehicleType.Type) |
                                @Html.ActionLink("View details", "Details", "Vehicles", new { id = vehicle.Id }, null)
                            </td>
                        </tr>
                    }
                }
            </table>
        </dd>
        @*nytt*@
        <dt>
            @Html.DisplayNameFor(x => x.ParkedVehicles) (checked out)

        <dd>
            <table>
                @foreach (var vehicle in Model.ParkedVehicles)
                {
                    if (vehicle.IsCheckedOut)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => vehicle.RegistrationNumber) |
                                @Html.DisplayFor(modelItem => vehicle.VehicleType.Type) |
                                @Html.ActionLink("View details", "Details", "Vehicles", new { id = vehicle.Id }, null)
                            </td>
                        </tr>
                    }
                }
            </table>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCGarage25/Views/Members/Edit.cshtml
@model MVCGarage25.Models.Member

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCGarage25/Views/Members/Index.cshtml
@model IEnumerable<MVCGarage25.Models.Member>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVCGarage25/Views/Members/Search.cshtml
@model IEnumerable<MVCGarage25.Models.Member>

@{
    ViewBag.Title = "Members in garage";
}

<h2>@ViewBag.SearchResultText</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>